# Ubuntu 20
# Run using:
# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i localhost -k -u $USER step02-vscode.yml
---
- name: Install Visual Studio Code
  hosts: localhost
  become_method: sudo
  tasks:
    - name: Add Apt signing key on remote server to keyring
      become: yes
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg

    - name: Add vscode repository into sources list
      become: yes
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
        filename: vscode

    - name: Install required packages
      become: yes
      apt:
        pkg:
          - apt-transport-https

    - name: Install VS Code
      become: yes
      apt:
        update_cache: yes
        pkg:
          - code

